#ifndef SENSORS_FXOS8700_REGS_H_
#define SENSORS_FXOS8700_REGS_H_

#define STATUS_00_REG        0x00
#define F_STATUS_REG         0x00
#define OUT_X_MSB_REG        0x01
#define OUT_X_LSB_REG        0x02
#define OUT_Y_MSB_REG        0x03
#define OUT_Y_LSB_REG        0x04
#define OUT_Z_MSB_REG        0x05
#define OUT_Z_LSB_REG        0x06
#define F_SETUP_REG          0x09
#define TRIG_CFG_REG         0x0A
#define SYSMOD_REG           0x0B
#define INT_SOURCE_REG       0x0C
#define WHO_AM_I_REG         0x0D
#define XYZ_DATA_CFG_REG     0x0E
#define HP_FILTER_CUTOFF_REG 0x0F
#define PL_STATUS_REG        0x10
#define PL_CFG_REG           0x11
#define PL_COUNT_REG         0x12
#define PL_BF_ZCOMP_REG      0x13
#define PL_P_L_THS_REG       0x14
#define FF_MT_CFG_REG        0x15
#define FF_MT_SRC_REG        0x16
#define FT_MT_THS_REG        0x17
#define TRANSIENT_THS_REG    0x1F
#define FF_MT_COUNT_REG      0x18
#define TRANSIENT_CFG_REG    0x1D
#define TRANSIENT_SRC_REG    0x1E
#define PULSE_CFG_REG        0x21
#define PULSE_SRC_REG        0x22
#define PULSE_THSX_REG       0x23
#define PULSE_THSY_REG       0x24
#define PULSE_THSZ_REG       0x25
#define PULSE_TMLT_REG       0x26
#define PULSE_LTCY_REG       0x27
#define PULSE_WIND_REG       0x28
#define ASLP_COUNT_REG       0x29
#define CTRL_REG1            0x2A
#define CTRL_REG2            0x2B
#define CTRL_REG3            0x2C
#define CTRL_REG4            0x2D
#define CTRL_REG5            0x2E
#define OFF_X_REG            0x2F
#define OFF_Y_REG            0x30
#define OFF_Z_REG            0x31
#define M_DR_STATUS_REG      0x32
#define M_OUT_X_MSB_REG      0x33
#define M_OUT_X_LSB_REG      0x34
#define M_OUT_Y_MSB_REG      0x35
#define M_OUT_Y_LSB_REG      0x36
#define M_OUT_Z_MSB_REG      0x37
#define M_OUT_Z_LSB_REG      0x38
#define CMP_X_MSB_REG        0x39
#define CMP_X_LSB_REG        0x3A
#define CMP_Y_MSB_REG        0x3B
#define CMP_Y_LSB_REG        0x3C
#define CMP_Z_MSB_REG        0x3D
#define CMP_Z_LSB_REG        0x3E
#define M_OFF_X_MSB_REG      0x3F
#define M_OFF_X_LSB_REG      0x40
#define M_OFF_Y_MSB_REG      0x41
#define M_OFF_Y_LSB_REG      0x42
#define M_OFF_Z_MSB_REG      0x43
#define M_OFF_Z_LSB_REG      0x44
#define MAX_X_MSB_REG        0x45
#define MAX_X_LSB_REG        0x46
#define MAX_Y_MSB_REG        0x47
#define MAX_Y_LSB_REG        0x48
#define MAX_Z_MSB_REG        0x49
#define MAX_Z_LSB_REG        0x4A
#define MIN_X_MSB_REG        0x4B
#define MIN_X_LSB_REG        0x4C
#define MIN_Y_MSB_REG        0x4D
#define MIN_Y_LSB_REG        0x4E
#define MIN_Z_MSB_REG        0x4F
#define MIN_Z_LSB_REG        0x50
#define TEMP_REG             0x51
#define M_THS_CFG_REG        0x52
#define M_THS_SRC_REG        0x53
#define M_THS_X_MSB_REG      0x54
#define M_THS_X_LSB_REG      0x55
#define M_THS_Y_MSB_REG      0x56
#define M_THS_Y_LSB_REG      0x57
#define M_THS_Z_MSB_REG      0x58
#define M_THS_Z_LSB_REG      0x59
#define M_THS_COUNT          0x5A
#define M_CTRL_REG1          0x5B
#define M_CTRL_REG2          0x5C
#define M_CTRL_REG3          0x5D
#define M_INT_SOURCE         0x5E
#define A_VECM_CFG           0x5F
#define A_VECM_THS_MSB       0x60
#define A_VECM_THS_LSB       0x61
#define A_VECM_CNT           0x62
#define A_VECM_INITX_MSB     0x63
#define A_VECM_INITX_LSB     0x64
#define A_VECM_INITY_MSB     0x65
#define A_VECM_INITY_LSB     0x66
#define A_VECM_INITZ_MSB     0x67
#define A_VECM_INITZ_LSB     0x68
#define M_VECM_CFG           0x69
#define M_VECM_THS_MSB       0x6A
#define M_VECM_THS_LSB       0x6B
#define M_VECM_CNT           0x6C
#define M_VECM_INITX_MSB     0x6D
#define M_VECM_INITX_LSB     0x6E
#define M_VECM_INITY_MSB     0x6F
#define M_VECM_INITY_LSB     0x70
#define M_VECM_INITZ_MSB     0x71
#define M_VECM_INITZ_LSB     0x72
#define A_FFMT_THS_X_MSB     0x73
#define A_FFMT_THS_X_LSB     0x74
#define A_FFMT_THS_Y_MSB     0x75
#define A_FFMT_THS_Y_LSB     0x76
#define A_FFMT_THS_Z_MSB     0x77
#define A_FFMT_THS_Z_LSB     0x78
#define A_TRAN_INIT_XYZ_MSB  0x79
#define A_TRAN_INIT_X_LSB    0x7A
#define A_TRAN_INIT_Y_LSB    0x7B
#define A_TRAN_INIT_Z_LSB    0x7C

#endif  // SENSORS_FXOS8700_REGS_H_
